"""
Project-wide constants.
All magic numbers live here — never hardcoded in pipeline code.
"""

# Time range
ACTUAL_START = "2023-01-01"
ACTUAL_END = "2026-06-30"
FORECAST_START = "2026-07-01"
FORECAST_END = "2027-12-31"

# Snapshot IDs (deterministic UUIDs)
SNAPSHOT_1_ID = "snap-2023-01-planning-cycle"
SNAPSHOT_2_ID = "snap-2024-01-planning-cycle"
SNAPSHOT_1_DATE = "2023-01-01"
SNAPSHOT_2_DATE = "2024-01-01"

# Forecast sources
FORECAST_SOURCE_PLANNER = "PLANNER"
FORECAST_SOURCE_PROPHET = "ML_PROPHET"
FORECAST_SOURCE_XGBOOST = "ML_XGBOOST"
FORECAST_SOURCE_LGBM = "ML_LIGHTGBM"
FORECAST_SOURCE_ENSEMBLE = "ML_ENSEMBLE"
FORECAST_SOURCE_CROSTON = "ML_CROSTON"

# Data types
DATA_TYPE_ACTUAL = "ACTUAL"
DATA_TYPE_FORECAST = "FORECAST"

# Product status
PRODUCT_STATUS_OLD = "OLD"
PRODUCT_STATUS_NPI = "NPI"

# Equipment types
EQUIP_TYPE_SYSTEM = "SYSTEM"
EQUIP_TYPE_FIXTURE = "FIXTURE"

# Capacity modes
CAP_MODE_NORMAL = "NORMAL"
CAP_MODE_MAXIMUM = "MAXIMUM"

# Retest types
RETEST_TYPE1 = "TYPE1"
RETEST_TYPE2 = "TYPE2"

# Bottleneck severity
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_HIGH = "HIGH"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_LOW = "LOW"
SEVERITY_BALANCED = "BALANCED"
SEVERITY_EXCESS = "EXCESS"

# Bottleneck thresholds (gap / demand)
THRESHOLD_CRITICAL = 0.15
THRESHOLD_HIGH = 0.08
THRESHOLD_MEDIUM = 0.03
THRESHOLD_LOW = 0.0
THRESHOLD_BALANCED = -0.05

# Capacity math
OTHER_IMPEDIMENTS_SEC = 0.0
DEFAULT_UTILIZATION = 0.85
RETEST_TIMES_TYPE1 = 2.0
TEST_X_PARAM_TYPE1 = 0.75

# Validation
MAX_YIELD = 0.99
MIN_YIELD = 0.50
MAX_DEMAND = 5000
MAX_EQUIP_QTY = 1000
MAX_TEST_TIME_SEC = 3000
MIN_TEST_TIME_SEC = 10

# Random seed (deterministic generation)
RANDOM_SEED = 42